/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow.API | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface BoardSpaceModel
 */
export interface BoardSpaceModel {
    /**
     * 
     * @type {number}
     * @memberof BoardSpaceModel
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BoardSpaceModel
     */
    name?: string | null;
}

/**
 * Check if a given object implements the BoardSpaceModel interface.
 */
export function instanceOfBoardSpaceModel(value: object): value is BoardSpaceModel {
    return true;
}

export function BoardSpaceModelFromJSON(json: any): BoardSpaceModel {
    return BoardSpaceModelFromJSONTyped(json, false);
}

export function BoardSpaceModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardSpaceModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function BoardSpaceModelToJSON(json: any): BoardSpaceModel {
    return BoardSpaceModelToJSONTyped(json, false);
}

export function BoardSpaceModelToJSONTyped(value?: BoardSpaceModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

