/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow.API | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerModel } from './PlayerModel';
import {
    PlayerModelFromJSON,
    PlayerModelFromJSONTyped,
    PlayerModelToJSON,
    PlayerModelToJSONTyped,
} from './PlayerModel';

/**
 * 
 * @export
 * @interface GameRequestModel
 */
export interface GameRequestModel {
    /**
     * 
     * @type {PlayerModel}
     * @memberof GameRequestModel
     */
    player?: PlayerModel;
}

/**
 * Check if a given object implements the GameRequestModel interface.
 */
export function instanceOfGameRequestModel(value: object): value is GameRequestModel {
    return true;
}

export function GameRequestModelFromJSON(json: any): GameRequestModel {
    return GameRequestModelFromJSONTyped(json, false);
}

export function GameRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'player': json['player'] == null ? undefined : PlayerModelFromJSON(json['player']),
    };
}

export function GameRequestModelToJSON(json: any): GameRequestModel {
    return GameRequestModelToJSONTyped(json, false);
}

export function GameRequestModelToJSONTyped(value?: GameRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'player': PlayerModelToJSON(value['player']),
    };
}

