/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow.API | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerModel } from './PlayerModel';
import {
    PlayerModelFromJSON,
    PlayerModelFromJSONTyped,
    PlayerModelToJSON,
    PlayerModelToJSONTyped,
} from './PlayerModel';
import type { GameModel } from './GameModel';
import {
    GameModelFromJSON,
    GameModelFromJSONTyped,
    GameModelToJSON,
    GameModelToJSONTyped,
} from './GameModel';

/**
 * 
 * @export
 * @interface GameResponseModel
 */
export interface GameResponseModel {
    /**
     * 
     * @type {PlayerModel}
     * @memberof GameResponseModel
     */
    currentPlayer?: PlayerModel;
    /**
     * 
     * @type {GameModel}
     * @memberof GameResponseModel
     */
    game?: GameModel;
}

/**
 * Check if a given object implements the GameResponseModel interface.
 */
export function instanceOfGameResponseModel(value: object): value is GameResponseModel {
    return true;
}

export function GameResponseModelFromJSON(json: any): GameResponseModel {
    return GameResponseModelFromJSONTyped(json, false);
}

export function GameResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPlayer': json['currentPlayer'] == null ? undefined : PlayerModelFromJSON(json['currentPlayer']),
        'game': json['game'] == null ? undefined : GameModelFromJSON(json['game']),
    };
}

export function GameResponseModelToJSON(json: any): GameResponseModel {
    return GameResponseModelToJSONTyped(json, false);
}

export function GameResponseModelToJSONTyped(value?: GameResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPlayer': PlayerModelToJSON(value['currentPlayer']),
        'game': GameModelToJSON(value['game']),
    };
}

