/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow.API | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PlayerModel
 */
export interface PlayerModel {
    /**
     * 
     * @type {string}
     * @memberof PlayerModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerModel
     */
    icon: string;
}

/**
 * Check if a given object implements the PlayerModel interface.
 */
export function instanceOfPlayerModel(value: object): value is PlayerModel {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    return true;
}

export function PlayerModelFromJSON(json: any): PlayerModel {
    return PlayerModelFromJSONTyped(json, false);
}

export function PlayerModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'icon': json['icon'],
    };
}

export function PlayerModelToJSON(json: any): PlayerModel {
    return PlayerModelToJSONTyped(json, false);
}

export function PlayerModelToJSONTyped(value?: PlayerModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'icon': value['icon'],
    };
}

