/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ActionTypeModel = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6
} as const;
export type ActionTypeModel = typeof ActionTypeModel[keyof typeof ActionTypeModel];


export function instanceOfActionTypeModel(value: any): boolean {
    for (const key in ActionTypeModel) {
        if (Object.prototype.hasOwnProperty.call(ActionTypeModel, key)) {
            if (ActionTypeModel[key as keyof typeof ActionTypeModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ActionTypeModelFromJSON(json: any): ActionTypeModel {
    return ActionTypeModelFromJSONTyped(json, false);
}

export function ActionTypeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionTypeModel {
    return json as ActionTypeModel;
}

export function ActionTypeModelToJSON(value?: ActionTypeModel | null): any {
    return value as any;
}

export function ActionTypeModelToJSONTyped(value: any, ignoreDiscriminator: boolean): ActionTypeModel {
    return value as ActionTypeModel;
}

