/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetModel
 */
export interface AssetModel {
    /**
     * 
     * @type {string}
     * @memberof AssetModel
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AssetModel
     */
    value?: number;
    /**
     * 
     * @type {number}
     * @memberof AssetModel
     */
    rateOfReturn?: number;
    /**
     * 
     * @type {number}
     * @memberof AssetModel
     */
    readonly income?: number;
}

/**
 * Check if a given object implements the AssetModel interface.
 */
export function instanceOfAssetModel(value: object): value is AssetModel {
    return true;
}

export function AssetModelFromJSON(json: any): AssetModel {
    return AssetModelFromJSONTyped(json, false);
}

export function AssetModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'value': json['value'] == null ? undefined : json['value'],
        'rateOfReturn': json['rateOfReturn'] == null ? undefined : json['rateOfReturn'],
        'income': json['income'] == null ? undefined : json['income'],
    };
}

export function AssetModelToJSON(json: any): AssetModel {
    return AssetModelToJSONTyped(json, false);
}

export function AssetModelToJSONTyped(value?: Omit<AssetModel, 'income'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
        'rateOfReturn': value['rateOfReturn'],
    };
}

