/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AssetTypeModel = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8
} as const;
export type AssetTypeModel = typeof AssetTypeModel[keyof typeof AssetTypeModel];


export function instanceOfAssetTypeModel(value: any): boolean {
    for (const key in AssetTypeModel) {
        if (Object.prototype.hasOwnProperty.call(AssetTypeModel, key)) {
            if (AssetTypeModel[key as keyof typeof AssetTypeModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AssetTypeModelFromJSON(json: any): AssetTypeModel {
    return AssetTypeModelFromJSONTyped(json, false);
}

export function AssetTypeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetTypeModel {
    return json as AssetTypeModel;
}

export function AssetTypeModelToJSON(value?: AssetTypeModel | null): any {
    return value as any;
}

export function AssetTypeModelToJSONTyped(value: any, ignoreDiscriminator: boolean): AssetTypeModel {
    return value as AssetTypeModel;
}

