/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuctionStateModel
 */
export interface AuctionStateModel {
    /**
     * 
     * @type {string}
     * @memberof AuctionStateModel
     */
    sellerId?: string;
    /**
     * 
     * @type {{ [key: string]: number | null; }}
     * @memberof AuctionStateModel
     */
    bids?: { [key: string]: number | null; } | null;
    /**
     * 
     * @type {string}
     * @memberof AuctionStateModel
     */
    winnerId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AuctionStateModel
     */
    winningBid?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof AuctionStateModel
     */
    isComplete?: boolean;
}

/**
 * Check if a given object implements the AuctionStateModel interface.
 */
export function instanceOfAuctionStateModel(value: object): value is AuctionStateModel {
    return true;
}

export function AuctionStateModelFromJSON(json: any): AuctionStateModel {
    return AuctionStateModelFromJSONTyped(json, false);
}

export function AuctionStateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuctionStateModel {
    if (json == null) {
        return json;
    }
    return {
        
        'sellerId': json['sellerId'] == null ? undefined : json['sellerId'],
        'bids': json['bids'] == null ? undefined : json['bids'],
        'winnerId': json['winnerId'] == null ? undefined : json['winnerId'],
        'winningBid': json['winningBid'] == null ? undefined : json['winningBid'],
        'isComplete': json['isComplete'] == null ? undefined : json['isComplete'],
    };
}

export function AuctionStateModelToJSON(json: any): AuctionStateModel {
    return AuctionStateModelToJSONTyped(json, false);
}

export function AuctionStateModelToJSONTyped(value?: AuctionStateModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sellerId': value['sellerId'],
        'bids': value['bids'],
        'winnerId': value['winnerId'],
        'winningBid': value['winningBid'],
        'isComplete': value['isComplete'],
    };
}

