/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActionTypeModel } from './ActionTypeModel';
import {
    ActionTypeModelFromJSON,
    ActionTypeModelFromJSONTyped,
    ActionTypeModelToJSON,
    ActionTypeModelToJSONTyped,
} from './ActionTypeModel';
import type { DoodadModel } from './DoodadModel';
import {
    DoodadModelFromJSON,
    DoodadModelFromJSONTyped,
    DoodadModelToJSON,
    DoodadModelToJSONTyped,
} from './DoodadModel';

/**
 * 
 * @export
 * @interface ConfirmActionModel
 */
export interface ConfirmActionModel {
    /**
     * 
     * @type {string}
     * @memberof ConfirmActionModel
     */
    readonly title?: string | null;
    /**
     * 
     * @type {ActionTypeModel}
     * @memberof ConfirmActionModel
     */
    name?: ActionTypeModel;
    /**
     * 
     * @type {boolean}
     * @memberof ConfirmActionModel
     */
    readonly isAnyPlayer?: boolean;
    /**
     * 
     * @type {DoodadModel}
     * @memberof ConfirmActionModel
     */
    doodad?: DoodadModel;
}



/**
 * Check if a given object implements the ConfirmActionModel interface.
 */
export function instanceOfConfirmActionModel(value: object): value is ConfirmActionModel {
    return true;
}

export function ConfirmActionModelFromJSON(json: any): ConfirmActionModel {
    return ConfirmActionModelFromJSONTyped(json, false);
}

export function ConfirmActionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmActionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'name': json['name'] == null ? undefined : ActionTypeModelFromJSON(json['name']),
        'isAnyPlayer': json['isAnyPlayer'] == null ? undefined : json['isAnyPlayer'],
        'doodad': json['doodad'] == null ? undefined : DoodadModelFromJSON(json['doodad']),
    };
}

export function ConfirmActionModelToJSON(json: any): ConfirmActionModel {
    return ConfirmActionModelToJSONTyped(json, false);
}

export function ConfirmActionModelToJSONTyped(value?: Omit<ConfirmActionModel, 'title'|'isAnyPlayer'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': ActionTypeModelToJSON(value['name']),
        'doodad': DoodadModelToJSON(value['doodad']),
    };
}

