/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActionTypeModel } from './ActionTypeModel';
import {
    ActionTypeModelFromJSON,
    ActionTypeModelFromJSONTyped,
    ActionTypeModelToJSON,
    ActionTypeModelToJSONTyped,
} from './ActionTypeModel';

/**
 * 
 * @export
 * @interface DealActionModel
 */
export interface DealActionModel {
    /**
     * 
     * @type {string}
     * @memberof DealActionModel
     */
    readonly title?: string | null;
    /**
     * 
     * @type {ActionTypeModel}
     * @memberof DealActionModel
     */
    name?: ActionTypeModel;
    /**
     * 
     * @type {boolean}
     * @memberof DealActionModel
     */
    readonly isAnyPlayer?: boolean;
}



/**
 * Check if a given object implements the DealActionModel interface.
 */
export function instanceOfDealActionModel(value: object): value is DealActionModel {
    return true;
}

export function DealActionModelFromJSON(json: any): DealActionModel {
    return DealActionModelFromJSONTyped(json, false);
}

export function DealActionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DealActionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'name': json['name'] == null ? undefined : ActionTypeModelFromJSON(json['name']),
        'isAnyPlayer': json['isAnyPlayer'] == null ? undefined : json['isAnyPlayer'],
    };
}

export function DealActionModelToJSON(json: any): DealActionModel {
    return DealActionModelToJSONTyped(json, false);
}

export function DealActionModelToJSONTyped(value?: Omit<DealActionModel, 'title'|'isAnyPlayer'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': ActionTypeModelToJSON(value['name']),
    };
}

