/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoodadModel
 */
export interface DoodadModel {
    /**
     * 
     * @type {string}
     * @memberof DoodadModel
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DoodadModel
     */
    cost?: number;
}

/**
 * Check if a given object implements the DoodadModel interface.
 */
export function instanceOfDoodadModel(value: object): value is DoodadModel {
    return true;
}

export function DoodadModelFromJSON(json: any): DoodadModel {
    return DoodadModelFromJSONTyped(json, false);
}

export function DoodadModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoodadModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'cost': json['cost'] == null ? undefined : json['cost'],
    };
}

export function DoodadModelToJSON(json: any): DoodadModel {
    return DoodadModelToJSONTyped(json, false);
}

export function DoodadModelToJSONTyped(value?: DoodadModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'cost': value['cost'],
    };
}

