/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiabilityModel
 */
export interface LiabilityModel {
    /**
     * 
     * @type {string}
     * @memberof LiabilityModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof LiabilityModel
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LiabilityModel
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof LiabilityModel
     */
    interestRate?: number;
    /**
     * 
     * @type {number}
     * @memberof LiabilityModel
     */
    term?: number;
    /**
     * 
     * @type {number}
     * @memberof LiabilityModel
     */
    readonly expense?: number;
}

/**
 * Check if a given object implements the LiabilityModel interface.
 */
export function instanceOfLiabilityModel(value: object): value is LiabilityModel {
    return true;
}

export function LiabilityModelFromJSON(json: any): LiabilityModel {
    return LiabilityModelFromJSONTyped(json, false);
}

export function LiabilityModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiabilityModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'interestRate': json['interestRate'] == null ? undefined : json['interestRate'],
        'term': json['term'] == null ? undefined : json['term'],
        'expense': json['expense'] == null ? undefined : json['expense'],
    };
}

export function LiabilityModelToJSON(json: any): LiabilityModel {
    return LiabilityModelToJSONTyped(json, false);
}

export function LiabilityModelToJSONTyped(value?: Omit<LiabilityModel, 'expense'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'amount': value['amount'],
        'interestRate': value['interestRate'],
        'term': value['term'],
    };
}

