/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PurchaseOfferModel } from './PurchaseOfferModel';
import {
    PurchaseOfferModelFromJSON,
    PurchaseOfferModelFromJSONTyped,
    PurchaseOfferModelToJSON,
    PurchaseOfferModelToJSONTyped,
} from './PurchaseOfferModel';
import type { ActionTypeModel } from './ActionTypeModel';
import {
    ActionTypeModelFromJSON,
    ActionTypeModelFromJSONTyped,
    ActionTypeModelToJSON,
    ActionTypeModelToJSONTyped,
} from './ActionTypeModel';

/**
 * 
 * @export
 * @interface MarketActionModel
 */
export interface MarketActionModel {
    /**
     * 
     * @type {string}
     * @memberof MarketActionModel
     */
    readonly title?: string | null;
    /**
     * 
     * @type {ActionTypeModel}
     * @memberof MarketActionModel
     */
    name?: ActionTypeModel;
    /**
     * 
     * @type {boolean}
     * @memberof MarketActionModel
     */
    readonly isAnyPlayer?: boolean;
    /**
     * 
     * @type {PurchaseOfferModel}
     * @memberof MarketActionModel
     */
    purchaseOffer?: PurchaseOfferModel;
    /**
     * 
     * @type {Set<string>}
     * @memberof MarketActionModel
     */
    playersResponded?: Set<string> | null;
}



/**
 * Check if a given object implements the MarketActionModel interface.
 */
export function instanceOfMarketActionModel(value: object): value is MarketActionModel {
    return true;
}

export function MarketActionModelFromJSON(json: any): MarketActionModel {
    return MarketActionModelFromJSONTyped(json, false);
}

export function MarketActionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketActionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'name': json['name'] == null ? undefined : ActionTypeModelFromJSON(json['name']),
        'isAnyPlayer': json['isAnyPlayer'] == null ? undefined : json['isAnyPlayer'],
        'purchaseOffer': json['purchaseOffer'] == null ? undefined : PurchaseOfferModelFromJSON(json['purchaseOffer']),
        'playersResponded': json['playersResponded'] == null ? undefined : new Set(json['playersResponded']),
    };
}

export function MarketActionModelToJSON(json: any): MarketActionModel {
    return MarketActionModelToJSONTyped(json, false);
}

export function MarketActionModelToJSONTyped(value?: Omit<MarketActionModel, 'title'|'isAnyPlayer'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': ActionTypeModelToJSON(value['name']),
        'purchaseOffer': PurchaseOfferModelToJSON(value['purchaseOffer']),
        'playersResponded': value['playersResponded'] == null ? undefined : Array.from(value['playersResponded'] as Set<any>),
    };
}

