/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProfessionModel } from './ProfessionModel';
import {
    ProfessionModelFromJSON,
    ProfessionModelFromJSONTyped,
    ProfessionModelToJSON,
    ProfessionModelToJSONTyped,
} from './ProfessionModel';

/**
 * 
 * @export
 * @interface PlayerOptionsModel
 */
export interface PlayerOptionsModel {
    /**
     * 
     * @type {Array<ProfessionModel>}
     * @memberof PlayerOptionsModel
     */
    professions?: Array<ProfessionModel> | null;
}

/**
 * Check if a given object implements the PlayerOptionsModel interface.
 */
export function instanceOfPlayerOptionsModel(value: object): value is PlayerOptionsModel {
    return true;
}

export function PlayerOptionsModelFromJSON(json: any): PlayerOptionsModel {
    return PlayerOptionsModelFromJSONTyped(json, false);
}

export function PlayerOptionsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerOptionsModel {
    if (json == null) {
        return json;
    }
    return {
        
        'professions': json['professions'] == null ? undefined : ((json['professions'] as Array<any>).map(ProfessionModelFromJSON)),
    };
}

export function PlayerOptionsModelToJSON(json: any): PlayerOptionsModel {
    return PlayerOptionsModelToJSONTyped(json, false);
}

export function PlayerOptionsModelToJSONTyped(value?: PlayerOptionsModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'professions': value['professions'] == null ? undefined : ((value['professions'] as Array<any>).map(ProfessionModelToJSON)),
    };
}

