/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetTypeModel } from './AssetTypeModel';
import {
    AssetTypeModelFromJSON,
    AssetTypeModelFromJSONTyped,
    AssetTypeModelToJSON,
    AssetTypeModelToJSONTyped,
} from './AssetTypeModel';

/**
 * 
 * @export
 * @interface PurchaseOfferModel
 */
export interface PurchaseOfferModel {
    /**
     * 
     * @type {string}
     * @memberof PurchaseOfferModel
     */
    name?: string | null;
    /**
     * 
     * @type {AssetTypeModel}
     * @memberof PurchaseOfferModel
     */
    type?: AssetTypeModel;
    /**
     * 
     * @type {number}
     * @memberof PurchaseOfferModel
     */
    price?: number;
}



/**
 * Check if a given object implements the PurchaseOfferModel interface.
 */
export function instanceOfPurchaseOfferModel(value: object): value is PurchaseOfferModel {
    return true;
}

export function PurchaseOfferModelFromJSON(json: any): PurchaseOfferModel {
    return PurchaseOfferModelFromJSONTyped(json, false);
}

export function PurchaseOfferModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseOfferModel {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : AssetTypeModelFromJSON(json['type']),
        'price': json['price'] == null ? undefined : json['price'],
    };
}

export function PurchaseOfferModelToJSON(json: any): PurchaseOfferModel {
    return PurchaseOfferModelToJSONTyped(json, false);
}

export function PurchaseOfferModelToJSONTyped(value?: PurchaseOfferModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': AssetTypeModelToJSON(value['type']),
        'price': value['price'],
    };
}

