/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StockStateModel } from './StockStateModel';
import {
    StockStateModelFromJSON,
    StockStateModelFromJSONTyped,
    StockStateModelToJSON,
    StockStateModelToJSONTyped,
} from './StockStateModel';

/**
 * 
 * @export
 * @interface StockMarketModel
 */
export interface StockMarketModel {
    /**
     * 
     * @type {Array<StockStateModel>}
     * @memberof StockMarketModel
     */
    stocks?: Array<StockStateModel> | null;
    /**
     * 
     * @type {number}
     * @memberof StockMarketModel
     */
    turnNumber?: number;
}

/**
 * Check if a given object implements the StockMarketModel interface.
 */
export function instanceOfStockMarketModel(value: object): value is StockMarketModel {
    return true;
}

export function StockMarketModelFromJSON(json: any): StockMarketModel {
    return StockMarketModelFromJSONTyped(json, false);
}

export function StockMarketModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockMarketModel {
    if (json == null) {
        return json;
    }
    return {
        
        'stocks': json['stocks'] == null ? undefined : ((json['stocks'] as Array<any>).map(StockStateModelFromJSON)),
        'turnNumber': json['turnNumber'] == null ? undefined : json['turnNumber'],
    };
}

export function StockMarketModelToJSON(json: any): StockMarketModel {
    return StockMarketModelToJSONTyped(json, false);
}

export function StockMarketModelToJSONTyped(value?: StockMarketModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stocks': value['stocks'] == null ? undefined : ((value['stocks'] as Array<any>).map(StockStateModelToJSON)),
        'turnNumber': value['turnNumber'],
    };
}

