/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StockPositionModel
 */
export interface StockPositionModel {
    /**
     * 
     * @type {string}
     * @memberof StockPositionModel
     */
    ticker?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StockPositionModel
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof StockPositionModel
     */
    averageCost?: number;
}

/**
 * Check if a given object implements the StockPositionModel interface.
 */
export function instanceOfStockPositionModel(value: object): value is StockPositionModel {
    return true;
}

export function StockPositionModelFromJSON(json: any): StockPositionModel {
    return StockPositionModelFromJSONTyped(json, false);
}

export function StockPositionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockPositionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'ticker': json['ticker'] == null ? undefined : json['ticker'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'averageCost': json['averageCost'] == null ? undefined : json['averageCost'],
    };
}

export function StockPositionModelToJSON(json: any): StockPositionModel {
    return StockPositionModelToJSONTyped(json, false);
}

export function StockPositionModelToJSONTyped(value?: StockPositionModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ticker': value['ticker'],
        'quantity': value['quantity'],
        'averageCost': value['averageCost'],
    };
}

