/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StockCategoryModel = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type StockCategoryModel = typeof StockCategoryModel[keyof typeof StockCategoryModel];


export function instanceOfStockCategoryModel(value: any): boolean {
    for (const key in StockCategoryModel) {
        if (Object.prototype.hasOwnProperty.call(StockCategoryModel, key)) {
            if (StockCategoryModel[key as keyof typeof StockCategoryModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StockCategoryModelFromJSON(json: any): StockCategoryModel {
    return StockCategoryModelFromJSONTyped(json, false);
}

export function StockCategoryModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockCategoryModel {
    return json as StockCategoryModel;
}

export function StockCategoryModelToJSON(value?: StockCategoryModel | null): any {
    return value as any;
}

export function StockCategoryModelToJSONTyped(value: any, ignoreDiscriminator: boolean): StockCategoryModel {
    return value as StockCategoryModel;
}

