/* tslint:disable */
/* eslint-disable */
/**
 * Cashflow API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StockCategoryModel } from './StockCategoryModel';
import {
    StockCategoryModelFromJSON,
    StockCategoryModelFromJSONTyped,
    StockCategoryModelToJSON,
    StockCategoryModelToJSONTyped,
} from './StockCategoryModel';

/**
 * 
 * @export
 * @interface StockStateModel
 */
export interface StockStateModel {
    /**
     * 
     * @type {string}
     * @memberof StockStateModel
     */
    ticker?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StockStateModel
     */
    name?: string | null;
    /**
     * 
     * @type {StockCategoryModel}
     * @memberof StockStateModel
     */
    category?: StockCategoryModel;
    /**
     * 
     * @type {number}
     * @memberof StockStateModel
     */
    currentPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof StockStateModel
     */
    previousPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof StockStateModel
     */
    dividendYield?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof StockStateModel
     */
    componentTickers?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof StockStateModel
     */
    readonly change?: number;
    /**
     * 
     * @type {number}
     * @memberof StockStateModel
     */
    readonly changePercent?: number;
}



/**
 * Check if a given object implements the StockStateModel interface.
 */
export function instanceOfStockStateModel(value: object): value is StockStateModel {
    return true;
}

export function StockStateModelFromJSON(json: any): StockStateModel {
    return StockStateModelFromJSONTyped(json, false);
}

export function StockStateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockStateModel {
    if (json == null) {
        return json;
    }
    return {
        
        'ticker': json['ticker'] == null ? undefined : json['ticker'],
        'name': json['name'] == null ? undefined : json['name'],
        'category': json['category'] == null ? undefined : StockCategoryModelFromJSON(json['category']),
        'currentPrice': json['currentPrice'] == null ? undefined : json['currentPrice'],
        'previousPrice': json['previousPrice'] == null ? undefined : json['previousPrice'],
        'dividendYield': json['dividendYield'] == null ? undefined : json['dividendYield'],
        'componentTickers': json['componentTickers'] == null ? undefined : json['componentTickers'],
        'change': json['change'] == null ? undefined : json['change'],
        'changePercent': json['changePercent'] == null ? undefined : json['changePercent'],
    };
}

export function StockStateModelToJSON(json: any): StockStateModel {
    return StockStateModelToJSONTyped(json, false);
}

export function StockStateModelToJSONTyped(value?: Omit<StockStateModel, 'change'|'changePercent'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ticker': value['ticker'],
        'name': value['name'],
        'category': StockCategoryModelToJSON(value['category']),
        'currentPrice': value['currentPrice'],
        'previousPrice': value['previousPrice'],
        'dividendYield': value['dividendYield'],
        'componentTickers': value['componentTickers'],
    };
}

